import CommonConstant from './CommonConstant';
const CarConstant = {
    Name: 'Name',
    Date: 'Date',
    Type: 'Type',
    Model: 'Model',
    Color: 'Color',
    Price: 'Price',
    FuelType: 'Fuel Type',
    Power: 'Power',
    MaximumSpeed: 'Maximum speed (km/h)',
    Length: 'Length',
    Width: 'Width',
    Displacement: 'Displacement (cc)',
    Images: 'Review',
    Equipments: "Equipments",
    Dealer: 'Dealer',
    Acceleration: '0-100 km/h',
    Upholstery: 'Upholstery',
    Transmission: 'Transmission',
    Torque: 'Torque',
    PageIndexDefault: 1,
    PageSizeDefault: 10,

    GetCarListMasterURL: `${CommonConstant.Server}/api/Car/car/master/list`,
    GetCarListAdminURL: `${CommonConstant.Server}/api/Car/car/admin/list`,
    GetAllCarMasterURL: `${CommonConstant.Server}/api/Car/car/master/listAll`,
    GetAllCarAdminURL: `${CommonConstant.Server}/api/Car/car/admin/listAll`,
    GetCarURL: `${CommonConstant.Server}/api/Car/car/get/`,
    CreateCarURL: `${CommonConstant.Server}/api/Car/api/car/create`,
    EditCarURL: `${CommonConstant.Server}/api/Car/api/car/edit/`,
    DisableCarURL: `${CommonConstant.Server}/api/Car/car/disable/`,
}
export default CarConstant;